spring:
  datasource:
    url: jdbc:mysql://192.168.1.48:3306/quartz_test?useUnicode=true
    username: root
    password: fpi123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: true
    prefix: classpath:/static/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity
    